### ISSUE TITLE
__Nonexhaustive in State

### ISSUE THREAD

**Issue by lucassardois** [svartalf/rust-battery#64]
While browsing the source code I found this:
https://docs.rs/battery/0.7.5/src/battery/types/state.rs.html#10-20

And more precisely this:
```
    // Awaiting for https://github.com/rust-lang/rust/issues/44109
    #[doc(hidden)]
    __Nonexhaustive,
```

It seems that the referenced issue has been closed. Is the __Nonexhaustive field still needed?

**Comment by svartalf** [comment]
`#[non_exhaustive]` attribute appeared in Rust 1.40.0 first, while this crate support Rust 1.36.0+ right now, therefore it is impossible to use it yet.
