### ISSUE TITLE
Battery rate graph should be in Watts instead of Wh

### ISSUE THREAD

**Issue by jherman3** [svartalf/rust-battery#9]
Discharge rate is a unit of power, watt-hours are energy. [The `energy_rate()` method](https://github.com/svartalf/rust-battery/blob/1e50430140fc3405c0dfe78329d0012d5e6d3663/battery/src/types/battery.rs#L35) returns `mW` so it looks like the CLI graph is using the wrong units.

**Comment by svartalf** [comment]
And done!
